# =================================================================
# Service: PostgreSQL 데이터베이스에 접근할 수 있는 안정적인 네트워크 주소를 제공합니다.
# - AI 엔진 서버는 이 서비스의 이름(postgres-service)을 통해 데이터베이스에 연결합니다.
# =================================================================
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: minwon-system
spec:
  ports:
    - port: 5432
  selector:
    # 'app: postgres' 레이블을 가진 Pod을 이 서비스와 연결합니다.
    app: postgres
  # Headless Service: 각 Pod에 고유한 DNS 주소를 할당하기 위해 ClusterIP를 사용하지 않습니다.
  # (예: postgres-0.postgres-service.minwon-system.svc.cluster.local)
  clusterIP: None
