# =================================================================
# StatefulSet: PostgreSQL 데이터베이스를 배포합니다.
# - 데이터베이스와 같이 상태 유지가 중요한 애플리케이션에 사용됩니다.
# - 각 Pod에 고유하고 안정적인 네트워크 이름과 저장 공간을 제공합니다.
# =================================================================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: minwon-system
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: pgvector/pgvector:pg16
          ports:
            - containerPort: 5432
              name: postgres
          # *** 핵심 수정: envFrom 대신 env를 사용하여 변수 이름을 직접 매핑합니다. ***
          env:
            # PostgreSQL 컨테이너가 필요로 하는 환경 변수 이름 (POSTGRES_USER)
            - name: POSTGRES_USER
              # 우리 Secret에 저장된 값 (key: PG_USER)을 참조합니다.
              valueFrom:
                secretKeyRef:
                  name: ai-engine-secrets
                  key: PG_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ai-engine-secrets
                  key: PG_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: ai-engine-secrets
                  key: PG_DATABASE
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
