# =================================================================
# PersistentVolumeClaim (PVC): 모델 파일을 저장할 영구 저장 공간을 요청합니다.
# - 이 PVC는 클러스터의 실제 저장 공간(PersistentVolume)과 연결되어,
#   Pod이 삭제되거나 재시작되어도 데이터가 안전하게 보존되도록 합니다.
# =================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: minwon-system
spec:
  # ReadWriteOnce: 한 번에 하나의 노드에서만 볼륨을 읽고 쓸 수 있도록 설정합니다.
  # 대부분의 스토리지 유형에서 지원하는 가장 일반적인 접근 모드입니다.
  accessModes:
    - ReadWriteOnce
  # 저장 공간 요청: 모델 파일들을 저장하기에 충분한 20GiB 크기를 요청합니다.
  resources:
    requests:
      storage: 20Gi
