# =================================================================
# Secret: AI 엔진의 민감한 정보를 안전하게 저장합니다.
# - 데이터베이스 연결에 필요한 모든 정보를 Secret에서 관리합니다.
# - 저장되는 값은 Base64로 인코딩되어야 합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: ai-engine-secrets
  namespace: minwon-system
type: Opaque
data:
  # PG_USER: "minwon_user" -> base64
  PG_USER: bWlud29uX3VzZXI=
  # PG_PASSWORD: "1234" -> base64
  PG_PASSWORD: MTIzNA==
  # PG_DATABASE: "minwon_pg_db" -> base64
  PG_DATABASE: bWlud29uX3BnX2Ri