# kubernetes-manifests/config-and-secrets.yaml

# AI 서버의 설정을 위한 ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-server-config
data:
  MODEL_PATH: "/app/model/gemma-3-1b-thinking-v2-q4_k_m.gguf"
  LLM_N_THREADS: "12"
  LLM_N_GPU_LAYERS: "-1"
  LLM_N_CTX: "2048"
  LLM_MAX_TOKENS: "256"
  # WSL 내부의 PostgreSQL 사용
  DB_HOST: "host.docker.internal"
  DB_PORT: "5432"
  DB_NAME: "minwon_pg_db"
  EMBEDDING_MODEL: "jhgan/ko-sroberta-multitask"
  LLM_N_BATCH: "1"
  LLM_REPEAT_PENALTY: "1.1"
  LLM_TEMPERATURE: "0.2"
---
# 전자정부 서버의 설정을 담는 ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: egov-globals-properties
data:
  globals.properties: |
    Globals.DriverClassName=com.mysql.cj.jdbc.Driver
    # [최종 수정] DB 접속 주소를 다시 host.minikube.internal 로 변경
    Globals.Url=jdbc:mysql://host.minikube.internal:3306/minwon_gov?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    Globals.UserName=gov_user
    Globals.Password=1234
    Globals.AiServerURL=http://ai-server-service:8000
---
# 데이터베이스 비밀번호를 위한 Secret
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  # '1234' -> MTIzNA==
  AI_DB_PASSWORD: "MTIzNA=="
  # 'minwon_user' -> bWlud29uX3VzZXI=
  AI_DB_USER: "bWlud29uX3VzZXI="
